import Head from "next/head";
import MainLayout from "@/layout/mainLayout";
import AddUserStyles from "@/styles/AddUser.module.scss";

const AddUser = () => {
  return (
    <>
      <Head>
        <title>Task Management System | Add User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <section className={AddUserStyles.add_user_main}>
          <div className={AddUserStyles.add_user_container}>
            <div className={AddUserStyles.title}>
              <h3>Create new User</h3>
            </div>
            <form className={AddUserStyles.form}>
              <div className={AddUserStyles.input_container}>
                {/* account credentials */}
                <div className={AddUserStyles.account_container}>
                  <p>Account Credentials</p>
                  <div>
                    <label htmlFor="email">Email</label>
                    <input
                      type="email"
                      name="email"
                      placeholder="Email"
                      required
                    />
                  </div>
                  <div>
                    <label htmlFor="username">Username</label>
                    <input
                      type="text"
                      name="username"
                      placeholder="username"
                      required
                    />
                  </div>
                  <div>
                    <label htmlFor="password">Password</label>
                    <input
                      type="password"
                      name="password"
                      placeholder="password"
                    />
                  </div>
                </div>

                {/* personal information */}
                <div className={AddUserStyles.personal_info}>
                  <p>Pesonal Information</p>
                  <div>
                    <label htmlFor="fname">First Name</label>
                    <input
                      type="text"
                      name="fname"
                      placeholder="First name"
                      required
                    />
                  </div>
                  <div>
                    <label htmlFor="lname">Last Name</label>
                    <input
                      type="text"
                      name="lname"
                      placeholder="Last name"
                      required
                    />
                  </div>
                  <div>
                    <label htmlFor="bday">Birth date</label>
                    <input type="date" name="bday" placeholder="bday" />
                  </div>
                  <div>
                    <label>Department</label>
                    <select>
                      <option value="">--Select Department--</option>
                      <option value="Front-end Developer">
                        Front-end Developer
                      </option>
                      <option value="Back-end Developer">
                        Back-end Developer
                      </option>
                      <option value="Marketing">Marketing</option>
                      <option value="HR">HR</option>
                    </select>
                  </div>
                  <div>
                    <label>Role</label>
                    <select>
                      <option value="">--Select Role--</option>
                      <option value="Admin">Administrator</option>
                      <option value="Employee">Employee</option>
                    </select>
                  </div>
                </div>
              </div>
              <div className={AddUserStyles.save_btn_container}>
                <button className={AddUserStyles.personal_info}>
                  Save new user
                </button>
              </div>
            </form>
          </div>
        </section>
      </MainLayout>
    </>
  );
};

export default AddUser;
