import Head from "next/head";
import Image from "next/image";
import MainLayout from "@/layout/mainLayout";
import homeStyles from "@/styles/Home.module.scss";
import TaskCard from "@/components/TaskCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Task Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className={homeStyles.home}>
          <div className={homeStyles.home_container}>
            <TaskCard />
            <TaskCard />
            <TaskCard />
          </div>
        </div>
      </MainLayout>
    </>
  );
}
